version: "3.8"

services:
    mongo:
        image: mongo:7
        command: ["mongod", "--auth"]
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_APP_USERNAME=${MONGO_APP_USERNAME}
            - MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}
            - MONGO_APP_DB=${MONGO_APP_DB}
        volumes:
            - mongo_main_data:/data/db
        configs:
            - source: mongo_init_js
              target: /docker-entrypoint-initdb.d/mongo-init.js
        deploy:
            update_config:
                order: stop-first
        networks:
            - internal

    app:
        image: ghcr.io/denikryt/feed-bot:${GIT_COMMIT_HASH:-latest}
        dns:
            - 8.8.8.8
            - 8.8.4.4
        environment:
            - MONGO_URI=mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo:27017/${MONGO_APP_DB}?authSource=${MONGO_APP_DB}
            - MONGO_DB=${MONGO_DB}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - ALLOWED_GUILD_IDS=${ALLOWED_GUILD_IDS}
            - MONGO_MESSAGE_MAPPING_COLLECTION=${MONGO_MESSAGE_MAPPING_COLLECTION:-message_mappings}
            - MONGO_GUILD_ROUTES_COLLECTION=${MONGO_GUILD_ROUTES_COLLECTION:-guild_routes}
            - MONGO_GUILD_PERMISSIONS_COLLECTION=${MONGO_GUILD_PERMISSIONS_COLLECTION:-guild_permissions}
            - LOG_FILE=${LOG_FILE:-logs/feed_bot.log}
        deploy:
            update_config:
                order: stop-first
        networks:
            - internal

networks:
    internal:

volumes:
    mongo_main_data:

configs:
    mongo_init_js:
        file: ./docker/mongo-init.js
