services:
  app:
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ALLOWED_GUILD_IDS: ${ALLOWED_GUILD_IDS}
      MONGO_URI: ${MONGO_URI:-mongodb://feedbot:password@host.docker.internal:27017/feed_database?authSource=feed_database}
      MONGO_DB: ${MONGO_DB:-feed_database}
      MONGO_MESSAGE_MAPPING_COLLECTION: ${MONGO_MESSAGE_MAPPING_COLLECTION:-message_mappings}
      MONGO_GUILD_ROUTES_COLLECTION: ${MONGO_GUILD_ROUTES_COLLECTION:-guild_routes}
      MONGO_GUILD_PERMISSIONS_COLLECTION: ${MONGO_GUILD_PERMISSIONS_COLLECTION:-guild_permissions}
      LOG_FILE: ${LOG_FILE:-logs/feed_bot.log}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
